### ISSUE TITLE
Using aiothrift server with a non-aiothrift client

### ISSUE THREAD

**Issue by thesamet** [moonshadow/aiothrift#4]
I am trying to get a thriftpy server to use aiothrift without changing the clients. When I send a request to the server I am getting the following exception:

```
2017-12-05 17:36:59,860 aiothrift[53]: CRITICAL unhandled app exception
Traceback (most recent call last):
  File "/home/thesamet/dev/tbcode/.pants.d/pyprep/requirements/CPython-3.5.3/3df7c8a19a9b0f11a6528cd277dcbb5b2e6c3adb/.deps/aiothrift-0.1-py3-none-any.whl/aiothrift/server.py", line 23, in __call__
    yield from self.processor.process(iproto, oproto)
  File "/home/thesamet/dev/tbcode/.pants.d/pyprep/requirements/CPython-3.5.3/3df7c8a19a9b0f11a6528cd277dcbb5b2e6c3adb/.deps/aiothrift-0.1-py3-none-any.whl/aiothrift/processor.py", line 71, in process
    api, seqid, result, call = yield from self.process_in(iprot)
  File "/home/thesamet/dev/tbcode/.pants.d/pyprep/requirements/CPython-3.5.3/3df7c8a19a9b0f11a6528cd277dcbb5b2e6c3adb/.deps/aiothrift-0.1-py3-none-any.whl/aiothrift/processor.py", line 18, in process_in
    api, type, seqid = yield from iprot.read_message_begin()
  File "/home/thesamet/dev/tbcode/.pants.d/pyprep/requirements/CPython-3.5.3/3df7c8a19a9b0f11a6528cd277dcbb5b2e6c3adb/.deps/aiothrift-0.1-py3-none-any.whl/aiothrift/protocol.py", line 425, in read_message_begin
    self.trans, strict=self.strict_read)
  File "/home/thesamet/dev/tbcode/.pants.d/pyprep/requirements/CPython-3.5.3/3df7c8a19a9b0f11a6528cd277dcbb5b2e6c3adb/.deps/aiothrift-0.1-py3-none-any.whl/aiothrift/protocol.py", line 176, in read_message_begin
    message='No protocol version header')
thriftpy.protocol.exc.TProtocolException: TProtocolException(type=4)
```

I see that the expectation of getting a version can be controlled by a variable named `strict_read`, but I don't see a way to control it as a user through `create_server()`.

I am not too familiar with the thrift wire format - is my client code being non-conforming if it doesn't send version information?

**Comment by ryanwang520** [comment]
Well, I just pick the version used by thriftpy, which is defined as a const in their codebase.
So if your client is implemented by thriftpy(which is strict_write by default), the version is exactly the same with the aiothrift server, which ensures that we speak the same language at each side. 

It is probably because that your client dose not `write_message_begin` with strict mode as you are not using a thriftpy client. Can you just hot patch the `read_message_begin` method, making `strict_read` false to see if it works? And I will consider to make the version check configurable at API level. If you have some good idea, welcome to send a PR.

btw,  aiothrift only support binary protocol currently, make sure that your client also uses the same protocol.

**Comment by thesamet** [comment]
Thanks @ryanwang520 , the client we use is thriftpy==0.3.9 - I believe we use binary protocol. I'll dig deeper to see what could be causing this problem.
